packages: []

catalogs:
  dev:
    '@types/node': 24.1.0
    globals: ^16.3.0
    local-pkg: ^1.1.1
    tsdown: ^0.13.0
    tsx: ^4.20.3
    typescript: 5.8.3

  lint:
    '@antfu/eslint-config': 5.0.0
    eslint: 9.32.0
    eslint-flat-config-utils: ^2.1.1
    eslint-typegen: ^2.3.0

  plugins:
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-sxzz: ^0.4.0
    eslint-plugin-unused-imports: ^4.1.4

onlyBuiltDependencies:
  - esbuild
